%Test FclustGRP function
%AUTHOR: Eric Fields
%VERSION DATE: 15 July 2017

global test_xls_output;
if isempty(test_xls_output)
    test_xls_output = true;
end

%Load GRP
if ispc()
    load('R:\Public\GK_lab\Eric\FMUT_development\FMUT\testing\data\Disflu_GroupLevel.GRP', '-mat');
elseif ismac()
    load('/Volumes/as-rsch-ncl1$/Public/GK_lab/Eric/FMUT_development/FMUT/testing/data/Disflu_GroupLevel.GRP', '-mat')
end

%Define general variables
time_wind = [300, 500];
n_perm = 100;
chan_hood = .9;
[~, start_sample] = min(abs( GRP.time_pts - time_wind(1) ));
[~, end_sample  ] = min(abs( GRP.time_pts - time_wind(2) ));

%% Exact interaction

if test_xls_output
    output_file = fullfile('outputs', 'FclustGRP_test.xlsx');
else
    output_file = false;
end
GRP = FclustGRP(GRP, ... 
              'bins',             4:7, ... 
              'bg_factor_name',   'reliability', ...
              'wg_factor_names',  {'expectedness', 'disfluency'}, ...
              'wg_factor_levels', [2, 2], ... 
              'time_wind',        time_wind, ...
              'n_perm',           n_perm, ...
              'alpha',            0.05, ... 
              'output_file',      output_file, ...
              'chan_hood',        chan_hood, ...
              'save_GRP',         'no');

%F==t^2
assert(all(all(GRP.F_tests(end).F_obs.expectednessXdisfluencyXreliability - GRP.grands_t(:, start_sample:end_sample, 78).^2 < 1e-4)));


%% One-way
%Completely randomized

if test_xls_output
    output_file = fullfile('outputs', 'FclustGRP_oneway_test.xlsx');
else
    output_file = false;
end 
GRP = FclustGRP(GRP, ... 
              'bins',             4, ... 
              'bg_factor_name',   'reliability', ...
              'time_wind',        time_wind, ...
              'n_perm',           n_perm, ...
              'alpha',            0.05, ... 
              'output_file',      output_file, ...
              'chan_hood',        chan_hood, ...
              'save_GRP',         'no');

%F==t^2
assert(all(all(GRP.F_tests(end).F_obs - GRP.grands_t(:, start_sample:end_sample, 4).^2 < 1e-4)));

%% Aproximate interaction

GRP = FclustGRP(GRP, ... 
              'bins',             [1, 4:9, 22:23],  ... 
              'bg_factor_name',   'reliability', ...
              'wg_factor_names',  {'expectedness', 'disfluency'}, ...
              'wg_factor_levels', [3, 3], ... 
              'time_wind',        time_wind, ...
              'n_perm',           n_perm, ...
              'chan_hood',        chan_hood, ...
              'plot_raster',      'no', ...
              'save_GRP',         'no');
          

%% Mean window

if test_xls_output
    output_file = fullfile('outputs', 'FclustGRP_meanwindow_test.xlsx');
else
    output_file = false;
end
GRP = FclustGRP(GRP, ... 
              'bins',             4:7, ... 
              'bg_factor_name',   'reliability', ...
              'wg_factor_names',  {'expectedness', 'disfluency'}, ...
              'wg_factor_levels', [2, 2], ... 
              'time_wind',        time_wind, ...
              'mean_wind',        'yes', ...
              'n_perm',           n_perm, ...
              'output_file',      output_file, ...
              'chan_hood',        chan_hood, ...
              'save_GRP',         'no');

