%Test FfdrGND function
%AUTHOR: Eric Fields
%VERSION DATE: 15 July 2017

global test_xls_output
if isempty(test_xls_output)
    test_xls_output = true;
end

%Load GRP
if ispc()
    load('R:\Public\GK_lab\Eric\FMUT_development\FMUT\testing\data\Disflu_GroupLevel.GRP', '-mat');
elseif ismac()
    load('/Volumes/as-rsch-ncl1$/Public/GK_lab/Eric/FMUT_development/FMUT/testing/data/Disflu_GroupLevel.GRP', '-mat')
end

%Define some general variables
time_wind = [300, 500];
[~, start_sample] = min(abs( GRP.time_pts - time_wind(1) ));
[~, end_sample  ] = min(abs( GRP.time_pts - time_wind(2) ));


%% BH

if test_xls_output
    output_file = fullfile('outputs', 'FfdrGRP_test.xlsx');
else
    output_file = false;
end 
GRP = FfdrGRP(GRP, ... 
              'bins',             4:7, ... 
              'bg_factor_name',   'reliability', ...
              'wg_factor_names',  {'expectedness', 'disfluency'}, ...
              'wg_factor_levels', [2, 2], ...
              'method',           'bh', ...
              'time_wind',        time_wind, ...
              'output_file',      output_file, ...
              'save_GRP',         'no');

%F==t^2
assert(all(all(GRP.F_tests(end).F_obs.expectednessXdisfluencyXreliability - GRP.grands_t(:, start_sample:end_sample, 78).^2 < 1e-4)));

          
%% One-way
%Completely randomized ANOVA

if test_xls_output
    output_file = fullfile('outputs', 'FfdrGRP_oneway_test.xlsx');
else
    output_file = false;
end 
GRP = FfdrGRP(GRP, ... 
              'bins',             4, ... 
              'bg_factor_name',   'reliability', ...
              'time_wind',        time_wind, ...
              'method',           'bh', ...
              'output_file',      output_file, ...
              'save_GRP',         'no');

%F==t^2
assert(all(all(GRP.F_tests(end).F_obs - GRP.grands_t(:, start_sample:end_sample, 4).^2 < 1e-4)));

GRP = tfdrGRP(GRP, 4, ...
              'time_wind', time_wind, ...
              'save_GRP', 'no', ...
              'plot_gui', 'no', ...
              'plot_raster', 'no', ...
              'verblevel', 2);
          
%p is the same
assert(all(GRP.F_tests(end).adj_pval(:) - GRP.t_tests(end).adj_pval(:) < 0.05));

          
%% Mean window

if test_xls_output
    output_file = fullfile('outputs', 'FfdrGRP_meanwindow_test.xlsx');
else
    output_file = false;
end 
GRP = FfdrGRP(GRP, ... 
              'bins',             4:7, ... 
              'bg_factor_name',   'reliability', ...
              'wg_factor_names',  {'expectedness', 'disfluency'}, ...
              'wg_factor_levels', [2, 2], ... 
              'time_wind',        time_wind, ...
              'mean_wind',        'yes', ...
              'output_file',      output_file, ...
              'save_GRP',         'no');
